# Site
title:              Luis Rocha
bio:                'Frontend web developer, designer, and photographer in San Francisco'
description:        "Luis Rocha - Frontend web developer, designer, and photographer in San Francisco"
logo:               'assets/img/logo.png'
locale:             en_US
# url:                http://luisrochadev.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   luisrochadev

# Social
email:              luisrochadev@gmail.com
twitter:            luisrochadev
github:             luisrochadev
linkedin:          luisrochadev

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
